// email notifications

pipeline {
    agent any

    environment {
        imageName = "custom"
        imageTag  = "v1"
    }

    // triggers {
    //     githubPush()
    //     cron('*/15 * * * *')
    // }

    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
    }

    stages {
        stage('SCM') {
            steps {
                sh '''
                git clone https://github.com/HighLandner/docker_agent.git
                ls -la
                '''
            }
        }
        stage('Docker build'){
            steps {
                script {
                    sh '''
                    pwd
                    '''
                    dockerImage = docker.build("${env.imageName}:${env.imageTag}")
                }
            }
        }
        stage('Docker push'){
            steps {
                script {
                    dockerImage.push()
                }
            }
        }
    }

    post {
        always {
            cleanWs deleteDirs: true
        }
    }
}
