pipeline {
    agent any
    triggers {
        githubPush()
        cron('*/15 * * * *')
    }
    stages {
        stage('Build') {
            steps {
                sh '''
                git clone https://github.com/HighLandner/docker_agent.git
                cd docker_agent
                docker build -t custom:v1 .
                '''
            }

            }
        }
}

